project:
  type: website
  preview: 
    port: 4200
  resources:
    - references.bib

website:
  title: "NeuroScope"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nicholas-monogioudis
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholas-monogioudis/
      - icon: instagram
        href: https://www.instagram.com/nicholasmonogioudis/

render:
- posts/neuroinflammation-part-1/index.qmd
- posts/neuroinflammation-part-2/index.qmd
- posts/neuroinflammation-part-3/index.qmd
- posts/neuroinflammation-part-4/index.qmd
- posts/neuroinflammation-part-5/index.qmd
- posts/neuroinflammation-part-6/index.qmd
- about.qmd
- index.qmd
- about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css